[package]
name = "halo2-pairing"
version = "0.1.0"
edition = "2021"

[patch.crates-io]
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v2022_06_03" }

[features]
dev-graph = ["halo2_proofs/dev-graph", "plotters"]

[dependencies]
rand = "0.8"
num-bigint = { version = "0.4", features = ["rand"] }
halo2_proofs = { version = "0.1.0-beta.1" }
plotters = { version = "0.3.0", optional = true }
tabbycat = { version = "0.1", features = ["attributes"], optional = true }
