[package]
name = "halo2-pairing"
version = "0.1.0"
edition = "2021"

[patch.crates-io]
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v2022_06_03" }

[features]
dev-graph = ["halo2_proofs/dev-graph", "plotters"]

[dependencies]
num-bigint = { version = "0.4", features = ["rand"] }
num-integer = "0.1"
num-traits = "0.2"
halo2_proofs = { version = "0.1.0-beta.1" }
plotters = { version = "0.3.0", optional = true }
tabbycat = { version = "0.1", features = ["attributes"], optional = true }
lazy_static = "1.4.0"
rand_core = { version = "0.6", default-features = false }
rand = "0.8"
