[package]
name = "halo2_ecc"
version = "0.0.1"
edition = "2021"

[patch.crates-io]
#halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v2022_06_03" }
#halo2_proofs = { git = "ssh://git@github.com/scroll-tech/halo2-gpu.git" }
#halo2_proofs = { path = "../halo2-gpu/halo2_proofs" }
halo2_proofs = { path = "../halo2-parallel/halo2_proofs" }

[features]
default = ["display"]
dev-graph = ["halo2_proofs/dev-graph", "plotters"]
display = []

[dependencies]
# subtle = "2.4"
num-bigint = { version = "0.4", features = ["rand"] }
num-integer = "0.1"
num-traits = "0.2"
halo2_proofs = { version = "0.1.0-beta.1" }
ff = "0.11.0"
group = "0.11"
halo2curves = { git = "https://github.com/jonathanpwang/pse-pairing-bn254.git", package = "pairing_bn254" }
# halo2curves = { git = "https://github.com/jonathanpwang/halo2curves.git", package = "halo2curves" }
plotters = { version = "0.3.0", optional = true }
tabbycat = { version = "0.1", features = ["attributes"], optional = true }
# lazy_static = "1.4.0"
rand_core = { version = "0.6", default-features = false }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
ark-std = { version = "0.3.0", features = ["print-trace"] }